sudo: false
language: node_js
node_js:
  - stable
install: npm update
script:
  - npm test
  - '[ "$TRAVIS_PULL_REQUEST" == "false" ] && npm run test-cloud || true'
cache:
  directories:
    - node_modules
deploy:
  provider: npm
  email: dominic@dbarnes.info
  api_key:
    secure: uAFSHg76QETa/nvNTDPypDJDSY2nbNP+5soGdiJDcRvvOM23fmjtP0LDATvXRmBGmx6hxXoj95WA08gCHouqmY9lOIPU1nP/Tg/qh2Saka1FCkSy782nh1o4SGmTj+/SLN/GDG1lmZHKVm22ngplB/FMNs79+2OznQK0911BSfnEkFmwUZMsko/ZytaHOjwBDlJwu4GTp5RBI6GP07E4X3Ir+7STajwpIUzb6i9lxgDf0Cb03qoWq+gk1fnUUkAAabPa3Zv/4zIwIeYOK6by/vCKJugbjUaFnZMBeSMhTmTzDfuLzF/198SDLipT1AbfbdxP41zqsaKDwxP8ov+H7WBNPI7mRxLymQjKJ/09ZEuKZNqYCa4N6nDychLJZq6+KluitDB/MjGrGU9I+5AYyJrHXdcA2vdqCPqaQGG8D2gxUrWSeFOLCnmBf9436pEhT17TmVMoe3ARgcYtZmaWGieT6eIHuTTEB+ZCz7MBLgufZ8+Nm/EO3UIlOC0hq/MqBXQBfPb1qWHLQyhwfeqTlIAfM61PZc7N5BS+LcmeugRN71Vv4UaqQqb84lWCGS8pH14EX8Xo2YoyQOAGBkgKixh5zxvAD0Vw/027CJTZGtdOP5wlZ69qU5KBl4qWijXNibgNveNvbSAOQoHFh4JR0MsiRK4cON5Q6nsskkBr3+8=
  on:
    tags: true
    repo: dominicbarnes/form-parse
env:
  global:
    - secure: BGjIzYR0jAI+DZOgJFFacFZUBDXGru30RifcE0YIpHbhY84h8X3ZgilONaKVif9Ms+3x3gVwGL0Cyc9LvJU8S1NbSwaImYwcUyCQRW2VD7DtCry3cJfWXiGsltMH2ECHY/M3kj2NSWjIAJjvgyKOEg9PZg/gdkuRZTRrAP8umC/U/g6k4ubH7t4YCy0bV3mUuPYgTbNRmV3M7Gq/F65C760SGaVJ9XmJbirU3vqmMkF3sKEQEA2aI2nAKfE/DP5T+8tVGtlzGU4NTMLz07ylY3xJ0khsj1apOmao/qe3lZ5vtCpPbov6CY/d5juQRJmxD7ESO7QzHZp76kkVB34yiWZXn5DOtABJUDqjl14+ofRGTYPa67zV0Rbf8k92MN18lz6jJEPLUJezbbDSp2FPLU78kT/PmlHHdyMIBgwO3pe2ToX3j+6BUEqAgi9x71wofJD01oHPEIc9RUtFekX/6hUriS1Edb0BbNZ83/NenGy1SfG3z2Kcx2sAqjsAIqLpsF1NC7tOYWMBnfNEokF0j1Bp33RcikytLLuKMdHn0VCL/fKQWU1BHQ3cCQ4UF5T9DW5JsvtNuozbXD44+/5WXx78rTtvoju2VGarHlBRBb0XrgqWq9husyHSvjlOJXTlY5nVvLxG8lZas/QEgfVuYeVGv03FbfsDUwuBhMcXDjQ=
    - secure: UMl6hvjgwH0vCrsgGl03bJugpNj2H3EWMwnw8xRm1uxPL3oZZh2Pv/9OLMy6kPn+wUbLNxBMSLyQCQAvxyOc3Kd6sytHfCwXnT1VdVv24f6bd28sd/dnM75TFpzSQ71Nu6ACibMUxoWjjZoVkIii0Uws73Up8AAK5CAcNuil58n2q24WkXR7lOITeKrcmkZNXXg03uVcJbH8owDuDz8xgqV2/WvcQQcZIHY58NtN9hlpbc7MI5gysKeMl+tcY4ddfEXdZFwfSx1GSmDLksFr0Q4S74Gyr+KkhNMh75u3zJWGUl1vBw6BKLRypilOok9J7YifR+E4LvpVZJkUxT566sGCCOirDRcBww9YDr7Nssu4rZI3ZRqb/LKQy9ow9YtUt7eOToAPKJqrxKmR43M6kf6aNyJ7vORzelMPbXJFsCLRgwF3BjXzKZJCGa3PGGK4Z9hL758FJQsuGDJCTLDlLw5PpvKPtODoXcTc5buO3k6by077J4d/soqivowO+SmTbelfkhFPxjfOAopG2ZTjVAIPthnFnciwfxjJEoXrwKuxQGYSC7k+t8s7itTKwSQEsb+Hg89AW71uJiSiVGxvD80KXxJNbndkahNnMCgj8JHzq64r6f34GMjMInqZITNas+HSvaGF/P9uDMh+7uqkyVa+Rwzwx8CDW/Oq3dy0mwY=
